export const THEME = '[theme] setTheme'
export const REGISTER = '[auth] register'
export const SIGNIN = '[auth] signin'
export const LOGOUT = '[auth] logout'
export const GETUSERS = '[users] getUsers'
export const ACTIVEUSER = '[users] active'
export const UPDATEUSER = '[users] update'
export const DELETEUSER = '[users] delete'
